import { generateSDKCode } from './generator';

export async function generateSDK(
  programName: string,
  programId: string,
  programCode: string
): Promise<string> {
  console.log('Generating SDK for program:', programName);

  try {
    const sdkCode = await generateSDKCode(programName, programId, programCode);
    
    // Wrap in a nice module format
    const wrappedSDK = `/**
 * ${programName} SDK
 * Program ID: ${programId}
 * Generated by SolForge Engine
 */

${sdkCode}

export const PROGRAM_ID = '${programId}';
`;

    return wrappedSDK;
  } catch (error) {
    console.error('SDK generation failed:', error);
    throw error;
  }
}
